CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE links (
  id INT PRIMARY KEY AUTO_INCREMENT,
  owner_id INT NULL,
  alias TEXT NOT NULL UNIQUE,
  original_url TEXT NOT NULL,
  click_count INT NOT NULL DEFAULT 0,
  expires_at DATETIME NULL DEFAULT (CURRENT_TIMESTAMP() + INTERVAL 30 MINUTE),
  FOREIGN KEY (owner_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);
